EXPORT_VM_HEADERS = paging.h

EXPORT_VM_C_SRCS = paging.c

EXPORT_VM_S_SRCS = 

HEADERS += $(addprefix vm/, $(EXPORT_VM_HEADERS))
C_SRCS += $(addprefix vm/, $(EXPORT_VM_C_SRCS))
S_SRCS += $(addprefix vm/, $(EXPORT_VM_S_SRCS))

DIRS += $(OBJ_DIR)/vm
