EXPORT_DEVICE_HEADERS = serial.h

EXPORT_DEVICE_C_SRCS = serial.c

EXPORT_DEVICE_S_SRCS = 

HEADERS += $(addprefix devices/, $(EXPORT_DEVICE_HEADERS))
C_SRCS += $(addprefix devices/, $(EXPORT_DEVICE_C_SRCS))
S_SRCS += $(addprefix devices/, $(EXPORT_DEVICE_S_SRCS))

DIRS += $(OBJ_DIR)/devices
